package com.sdxxtop.trackerlibrary.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sdxxtop.trackerlibrary.db.entity.TrackerPathEntry;

import com.sdxxtop.trackerlibrary.db.TrackerPathEntryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig trackerPathEntryDaoConfig;

    private final TrackerPathEntryDao trackerPathEntryDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        trackerPathEntryDaoConfig = daoConfigMap.get(TrackerPathEntryDao.class).clone();
        trackerPathEntryDaoConfig.initIdentityScope(type);

        trackerPathEntryDao = new TrackerPathEntryDao(trackerPathEntryDaoConfig, this);

        registerDao(TrackerPathEntry.class, trackerPathEntryDao);
    }
    
    public void clear() {
        trackerPathEntryDaoConfig.clearIdentityScope();
    }

    public TrackerPathEntryDao getTrackerPathEntryDao() {
        return trackerPathEntryDao;
    }

}
